volumes:
  clojure_dev:
    driver: local

networks:
  clojure_dev:
    driver: bridge

services:
  clojure-dev:
    container_name: clojure-dev
    image: clojure-dev:0.0

    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USER: franco
        UID: 1000
        HOME: /home/franco

    environment:
      - TERM=xterm-256color
      - LANG=c.UTF-8

      # If on OSX (Docker Desktop)
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - clojure_dev:$HOME

      # Map local clojure tool configs to container.
      - $HOME/.clojure:$HOME/.clojure
      - $HOME/.lein:$HOME/.lein

      # If using git from within container.
      - $HOME/.gitconfig:$HOME/.gitconfig
      - $HOME/.gnupg:$HOME/.gnupg
      - $HOME/.ssh:$HOME/.ssh

      # If using tmux in the container.
      - $HOME/.tmux.conf:$HOME/.tmux.conf
      - $HOME/.tmux:$HOME/.tmux

      # If using neovim in the container.
      - $HOME/.config/nvim:$HOME/.config/nvim

      # Map the local project repo into the container.
      - $PROJECT_HOME:$HOME/project

      # Allow for docker control.
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - clojure_dev
